2018-10-20 20:27:33.216 [error] <0.494.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.499.0> exit with reason normal in context child_terminated
2018-10-20 20:27:34.519 [error] emulator Error in process <0.613.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:27:35.528 [error] emulator Error in process <0.629.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:27:36.533 [error] emulator Error in process <0.645.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:27:37.541 [error] emulator Error in process <0.661.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
